# Generated by Django 4.1.7 on 2023-04-08 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('wait', 'Wait'), ('game', 'Game')], default='wait', max_length=4)),
                ('players', models.ManyToManyField(related_name='games_as_player', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='games_as_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
