# Generated by Django 4.1.7 on 2023-04-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_game_players_remove_game_users_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='games_as_players', to='app.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='games_as_users', to='app.player'),
        ),
    ]
