# Generated by Django 4.2.1 on 2023-05-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='users',
        ),
        migrations.AddField(
            model_name='game',
            name='visitors',
            field=models.ManyToManyField(blank=True, related_name='games_as_visitors', to='app.player'),
        ),
    ]
