# Generated by Django 4.2.1 on 2023-05-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_game_users_game_visitors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AddField(
            model_name='game',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='games_as_participants', to='app.player'),
        ),
    ]
