# Generated by Django 4.2.1 on 2023-05-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_game_current_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active_players',
            field=models.ManyToManyField(blank=True, related_name='games_as_active_players', to='app.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='allowed_actions',
            field=models.CharField(choices=[('play', 'Play'), ('take', 'Take'), ('pass', 'Pass')], default='play', max_length=4),
        ),
        migrations.AddField(
            model_name='game',
            name='phase',
            field=models.CharField(choices=[('attack', 'Attack'), ('defense', 'Defense')], default='attack', max_length=7),
        ),
    ]
