# Generated by Django 4.2.1 on 2023-05-25 21:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_game_active_players_game_allowed_actions_game_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='allowed_actions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('play', 'Play'), ('take', 'Take'), ('pass', 'Pass')], default='play', max_length=4), blank=True, default=list, size=None),
        ),
    ]
