# Generated by Django 4.2.1 on 2023-05-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_game_allowed_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('suit', models.CharField(choices=[('H', 'Hearts'), ('D', 'Diamonds'), ('C', 'Clubs'), ('S', 'Spades')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='deck',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='player',
            name='hand',
            field=models.JSONField(default=list),
        ),
    ]
