# Generated by Django 4.2.1 on 2023-05-26 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_card_game_deck_player_hand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hand',
        ),
        migrations.AddField(
            model_name='card',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deck', to='app.game'),
        ),
        migrations.AddField(
            model_name='card',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hand', to='app.player'),
        ),
    ]
