# Generated by Django 4.2.1 on 2023-05-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_game_deck_remove_player_hand_card_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='order_in_deck',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
