# Generated by Django 4.2.1 on 2023-05-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_card_order_in_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='deck',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='table',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='player',
            name='hand',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
