# Generated by Django 4.2.1 on 2024-03-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_game_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='phase',
            field=models.CharField(choices=[('attack', 'Attack'), ('defense', 'Defense'), ('addition', 'Addition')], default='attack', max_length=15),
        ),
    ]
